name: Deploy package to GitHub package registry
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Setup actions'
        uses: actions/checkout@v1
      - name: 'npm/registry setup'
        uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'publish package'
        run: |
          echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> ~/.npmrc
          npm run test 
          npm run build
          npm config list 
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
